packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@clerk/shared': false
  lefthook: false
  sharp: false
blockExoticSubdeps: true # https://pnpm.io/settings#blockexoticsubdeps
catalog:
  hono: 4.12.16

catalogs:
  next.js:
    next: 15.5.15
    react: 19.2.5
    react-dom: 19.2.5

minimumReleaseAge: 5760 # no updates younger than 4 days

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'eslint-import-resolver-typescript@3.10.1'
  - 'semver@6.3.1'
  - '@eslint/core@0.10.0'
