export type ColorId = keyof typeof colors

const colors = {
  noColor: { id: 'noColor', name: 'No color', hex: 'transparent' },
  aliceblue: { id: 'aliceblue', name: 'Alice Blue', hex: '#F0F8FF' },
  antiquewhite: { id: 'antiquewhite', name: 'Antique White', hex: '#FAEBD7' },
  aqua: { id: 'aqua', name: 'Aqua', hex: '#00FFFF' },
  aquamarine: { id: 'aquamarine', name: 'Aquamarine', hex: '#7FFFD4' },
  azure: { id: 'azure', name: 'Azure', hex: '#F0FFFF' },
  beige: { id: 'beige', name: 'Beige', hex: '#F5F5DC' },
  bisque: { id: 'bisque', name: 'Bisque', hex: '#FFE4C4' },
  black: { id: 'black', name: 'Black', hex: '#000000' },
  blanchedalmond: { id: 'blanchedalmond', name: 'Blanched Almond', hex: '#FFEBCD' },
  blue: { id: 'blue', name: 'Blue', hex: '#0000FF' },
  blueviolet: { id: 'blueviolet', name: 'Blue Violet', hex: '#8A2BE2' },
  brown: { id: 'brown', name: 'Brown', hex: '#A52A2A' },
  burlywood: { id: 'burlywood', name: 'Burly Wood', hex: '#DEB887' },
  cadetblue: { id: 'cadetblue', name: 'Cadet Blue', hex: '#5F9EA0' },
  chartreuse: { id: 'chartreuse', name: 'Chartreuse', hex: '#7FFF00' },
  chocolate: { id: 'chocolate', name: 'Chocolate', hex: '#D2691E' },
  coral: { id: 'coral', name: 'Coral', hex: '#FF7F50' },
  cornflowerblue: { id: 'cornflowerblue', name: 'Cornflower Blue', hex: '#6495ED' },
  cornsilk: { id: 'cornsilk', name: 'Cornsilk', hex: '#FFF8DC' },
  crimson: { id: 'crimson', name: 'Crimson', hex: '#DC143C' },
  cyan: { id: 'cyan', name: 'Cyan', hex: '#00FFFF' },
  darkblue: { id: 'darkblue', name: 'Dark Blue', hex: '#00008B' },
  darkcyan: { id: 'darkcyan', name: 'Dark Cyan', hex: '#008B8B' },
  darkgoldenrod: { id: 'darkgoldenrod', name: 'Dark Goldenrod', hex: '#B8860B' },
  darkgray: { id: 'darkgray', name: 'Dark Gray', hex: '#A9A9A9' },
  darkgreen: { id: 'darkgreen', name: 'Dark Green', hex: '#006400' },
  darkgrey: { id: 'darkgrey', name: 'Dark Grey', hex: '#A9A9A9' },
  darkkhaki: { id: 'darkkhaki', name: 'Dark Khaki', hex: '#BDB76B' },
  darkmagenta: { id: 'darkmagenta', name: 'Dark Magenta', hex: '#8B008B' },
  darkolivegreen: { id: 'darkolivegreen', name: 'Dark Olive Green', hex: '#556B2F' },
  darkorange: { id: 'darkorange', name: 'Dark Orange', hex: '#FF8C00' },
  darkorchid: { id: 'darkorchid', name: 'Dark Orchid', hex: '#9932CC' },
  darkred: { id: 'darkred', name: 'Dark Red', hex: '#8B0000' },
  darksalmon: { id: 'darksalmon', name: 'Dark Salmon', hex: '#E9967A' },
  darkseagreen: { id: 'darkseagreen', name: 'Dark Sea Green', hex: '#8FBC8F' },
  darkslateblue: { id: 'darkslateblue', name: 'Dark Slate Blue', hex: '#483D8B' },
  darkslategray: { id: 'darkslategray', name: 'Dark Slate Gray', hex: '#2F4F4F' },
  darkslategrey: { id: 'darkslategrey', name: 'Dark Slate Grey', hex: '#2F4F4F' },
  darkturquoise: { id: 'darkturquoise', name: 'Dark Turquoise', hex: '#00CED1' },
  darkviolet: { id: 'darkviolet', name: 'Dark Violet', hex: '#9400D3' },
  deeppink: { id: 'deeppink', name: 'Deep Pink', hex: '#FF1493' },
  deepskyblue: { id: 'deepskyblue', name: 'Deep Sky Blue', hex: '#00BFFF' },
  dimgray: { id: 'dimgray', name: 'Dim Gray', hex: '#696969' },
  dimgrey: { id: 'dimgrey', name: 'Dim Grey', hex: '#696969' },
  dodgerblue: { id: 'dodgerblue', name: 'Dodger Blue', hex: '#1E90FF' },
  firebrick: { id: 'firebrick', name: 'Fire Brick', hex: '#B22222' },
  floralwhite: { id: 'floralwhite', name: 'Floral White', hex: '#FFFAF0' },
  forestgreen: { id: 'forestgreen', name: 'Forest Green', hex: '#228B22' },
  fuchsia: { id: 'fuchsia', name: 'Fuchsia', hex: '#FF00FF' },
  gainsboro: { id: 'gainsboro', name: 'Gainsboro', hex: '#DCDCDC' },
  ghostwhite: { id: 'ghostwhite', name: 'Ghost White', hex: '#F8F8FF' },
  gold: { id: 'gold', name: 'Gold', hex: '#FFD700' },
  goldenrod: { id: 'goldenrod', name: 'Goldenrod', hex: '#DAA520' },
  gray: { id: 'gray', name: 'Gray', hex: '#808080' },
  green: { id: 'green', name: 'Green', hex: '#008000' },
  greenyellow: { id: 'greenyellow', name: 'Green Yellow', hex: '#ADFF2F' },
  grey: { id: 'grey', name: 'Grey', hex: '#808080' },
  honeydew: { id: 'honeydew', name: 'Honeydew', hex: '#F0FFF0' },
  hotpink: { id: 'hotpink', name: 'Hot Pink', hex: '#FF69B4' },
  indianred: { id: 'indianred', name: 'Indian Red', hex: '#CD5C5C' },
  indigo: { id: 'indigo', name: 'Indigo', hex: '#4B0082' },
  ivory: { id: 'ivory', name: 'Ivory', hex: '#FFFFF0' },
  khaki: { id: 'khaki', name: 'Khaki', hex: '#F0E68C' },
  lavender: { id: 'lavender', name: 'Lavender', hex: '#E6E6FA' },
  lavenderblush: { id: 'lavenderblush', name: 'Lavender Blush', hex: '#FFF0F5' },
  lawngreen: { id: 'lawngreen', name: 'Lawn Green', hex: '#7CFC00' },
  lemonchiffon: { id: 'lemonchiffon', name: 'Lemon Chiffon', hex: '#FFFACD' },
  lightblue: { id: 'lightblue', name: 'Light Blue', hex: '#ADD8E6' },
  lightcoral: { id: 'lightcoral', name: 'Light Coral', hex: '#F08080' },
  lightcyan: { id: 'lightcyan', name: 'Light Cyan', hex: '#E0FFFF' },
  lightgoldenrodyellow: { id: 'lightgoldenrodyellow', name: 'Light Goldenrod Yellow', hex: '#FAFAD2' },
  lightgray: { id: 'lightgray', name: 'Light Gray', hex: '#D3D3D3' },
  lightgreen: { id: 'lightgreen', name: 'Light Green', hex: '#90EE90' },
  lightgrey: { id: 'lightgrey', name: 'Light Grey', hex: '#D3D3D3' },
  lightpink: { id: 'lightpink', name: 'Light Pink', hex: '#FFB6C1' },
  lightsalmon: { id: 'lightsalmon', name: 'Light Salmon', hex: '#FFA07A' },
  lightseagreen: { id: 'lightseagreen', name: 'Light Sea Green', hex: '#20B2AA' },
  lightskyblue: { id: 'lightskyblue', name: 'Light Sky Blue', hex: '#87CEFA' },
  lightslategray: { id: 'lightslategray', name: 'Light Slate Gray', hex: '#778899' },
  lightslategrey: { id: 'lightslategrey', name: 'Light Slate Grey', hex: '#778899' },
  lightsteelblue: { id: 'lightsteelblue', name: 'Light Steel Blue', hex: '#B0C4DE' },
  lightyellow: { id: 'lightyellow', name: 'Light Yellow', hex: '#FFFFE0' },
  lime: { id: 'lime', name: 'Lime', hex: '#00FF00' },
  limegreen: { id: 'limegreen', name: 'Lime Green', hex: '#32CD32' },
  linen: { id: 'linen', name: 'Linen', hex: '#FAF0E6' },
  magenta: { id: 'magenta', name: 'Magenta', hex: '#FF00FF' },
  maroon: { id: 'maroon', name: 'Maroon', hex: '#800000' },
  mediumaquamarine: { id: 'mediumaquamarine', name: 'Medium Aquamarine', hex: '#66CDAA' },
  mediumblue: { id: 'mediumblue', name: 'Medium Blue', hex: '#0000CD' },
  mediumorchid: { id: 'mediumorchid', name: 'Medium Orchid', hex: '#BA55D3' },
  mediumpurple: { id: 'mediumpurple', name: 'Medium Purple', hex: '#9370DB' },
  mediumseagreen: { id: 'mediumseagreen', name: 'Medium Sea Green', hex: '#3CB371' },
  mediumslateblue: { id: 'mediumslateblue', name: 'Medium Slate Blue', hex: '#7B68EE' },
  mediumspringgreen: { id: 'mediumspringgreen', name: 'Medium Spring Green', hex: '#00FA9A' },
  mediumturquoise: { id: 'mediumturquoise', name: 'Medium Turquoise', hex: '#48D1CC' },
  mediumvioletred: { id: 'mediumvioletred', name: 'Medium Violet Red', hex: '#C71585' },
  midnightblue: { id: 'midnightblue', name: 'Midnight Blue', hex: '#191970' },
  mintcream: { id: 'mintcream', name: 'Mint Cream', hex: '#F5FFFA' },
  mistyrose: { id: 'mistyrose', name: 'Misty Rose', hex: '#FFE4E1' },
  moccasin: { id: 'moccasin', name: 'Moccasin', hex: '#FFE4B5' },
  navajowhite: { id: 'navajowhite', name: 'Navajo White', hex: '#FFDEAD' },
  navy: { id: 'navy', name: 'Navy', hex: '#000080' },
  oldlace: { id: 'oldlace', name: 'Old Lace', hex: '#FDF5E6' },
  olive: { id: 'olive', name: 'Olive', hex: '#808000' },
  olivedrab: { id: 'olivedrab', name: 'Olive Drab', hex: '#6B8E23' },
  orange: { id: 'orange', name: 'Orange', hex: '#FFA500' },
  orangered: { id: 'orangered', name: 'Orange Red', hex: '#FF4500' },
  orchid: { id: 'orchid', name: 'Orchid', hex: '#DA70D6' },
  palegoldenrod: { id: 'palegoldenrod', name: 'Pale Goldenrod', hex: '#EEE8AA' },
  palegreen: { id: 'palegreen', name: 'Pale Green', hex: '#98FB98' },
  paleturquoise: { id: 'paleturquoise', name: 'Pale Turquoise', hex: '#AFEEEE' },
  palevioletred: { id: 'palevioletred', name: 'Pale Violet Red', hex: '#DB7093' },
  papayawhip: { id: 'papayawhip', name: 'Papaya Whip', hex: '#FFEFD5' },
  peachpuff: { id: 'peachpuff', name: 'Peach Puff', hex: '#FFDAB9' },
  peru: { id: 'peru', name: 'Peru', hex: '#CD853F' },
  pink: { id: 'pink', name: 'Pink', hex: '#FFC0CB' },
  plum: { id: 'plum', name: 'Plum', hex: '#DDA0DD' },
  powderblue: { id: 'powderblue', name: 'Powder Blue', hex: '#B0E0E6' },
  purple: { id: 'purple', name: 'Purple', hex: '#800080' },
  rebeccapurple: { id: 'rebeccapurple', name: 'Rebecca Purple', hex: '#663399' },
  red: { id: 'red', name: 'Red', hex: '#FF0000' },
  rosybrown: { id: 'rosybrown', name: 'Rosy Brown', hex: '#BC8F8F' },
  royalblue: { id: 'royalblue', name: 'Royal Blue', hex: '#4169E1' },
  saddlebrown: { id: 'saddlebrown', name: 'Saddle Brown', hex: '#8B4513' },
  salmon: { id: 'salmon', name: 'Salmon', hex: '#FA8072' },
  sandybrown: { id: 'sandybrown', name: 'Sandy Brown', hex: '#F4A460' },
  seagreen: { id: 'seagreen', name: 'Sea Green', hex: '#2E8B57' },
  seashell: { id: 'seashell', name: 'Seashell', hex: '#FFF5EE' },
  sienna: { id: 'sienna', name: 'Sienna', hex: '#A0522D' },
  silver: { id: 'silver', name: 'Silver', hex: '#C0C0C0' },
  skyblue: { id: 'skyblue', name: 'Sky Blue', hex: '#87CEEB' },
  slateblue: { id: 'slateblue', name: 'Slate Blue', hex: '#6A5ACD' },
  slategray: { id: 'slategray', name: 'Slate Gray', hex: '#708090' },
  slategrey: { id: 'slategrey', name: 'Slate Grey', hex: '#708090' },
  snow: { id: 'snow', name: 'Snow', hex: '#FFFAFA' },
  springgreen: { id: 'springgreen', name: 'Spring Green', hex: '#00FF7F' },
  steelblue: { id: 'steelblue', name: 'Steel Blue', hex: '#4682B4' },
  tan: { id: 'tan', name: 'Tan', hex: '#D2B48C' },
  teal: { id: 'teal', name: 'Teal', hex: '#008080' },
  thistle: { id: 'thistle', name: 'Thistle', hex: '#D8BFD8' },
  tomato: { id: 'tomato', name: 'Tomato', hex: '#FF6347' },
  turquoise: { id: 'turquoise', name: 'Turquoise', hex: '#40E0D0' },
  violet: { id: 'violet', name: 'Violet', hex: '#EE82EE' },
  wheat: { id: 'wheat', name: 'Wheat', hex: '#F5DEB3' },
  white: { id: 'white', name: 'White', hex: '#FFFFFF' },
  whitesmoke: { id: 'whitesmoke', name: 'White Smoke', hex: '#F5F5F5' },
  yellow: { id: 'yellow', name: 'Yellow', hex: '#FFFF00' },
  yellowgreen: { id: 'yellowgreen', name: 'Yellow Green', hex: '#9ACD32' },
} as const

export default colors
